# type_erorres

# SyntaxError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'hello world'
  File "<stdin>", line 1
    print 'hello world'
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?
>>>

se esta intentado hacer un print de un string sin ponerle al print sus (), para solucionarlo print("hello world)
'''

# NameError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(age)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'age' is not defined
>>>

estamos intentado hacer print de una variable q no fue declarada, para solucionarlo hay q declarar la variable age y asignarle algun valor
'''

# IndexError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> numbers = [1, 2, 3, 4, 5]
>>> numbers[5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>>

out of range es un error q pasa cunado se intenta acceder al elemento de la lista en la posicion 5 pero solo tenemos hasta la 4,
para solucinarlo o agragamos un elemento mas a la list de numeros o accedemos a los valores entre 0 a len(numbers)
'''

# ModuleNotFoundError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import maths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'maths'
>>>

en este ejem al importar math se lo llama con una s de mas por lo cual el modulo no esta bien importado, para solucionarlo importarlo con el nombre correcto o deja q el autocompletar del visual haga el trabajo (cuidado xq puede importarlo mal o cualquier otra cosa)
'''

# AttributeError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import maths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'maths'
>>> import math
>>> math.PI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'math' has no attribute 'PI'
>>>

se intenta lammar a la funcion de pi pero con mayusculas, lo cual PI no existe dentro del modulo math, para solucionarlo cambiar PI por pi
'''

# KeyError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> users = {'name':'Asab', 'age':250, 'country':'Finland'}
>>> users['name']
'Asab'
>>> users['county']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'county'
>>>

la key para llamar al pais es incorrecta ya q se puso county en ves de country (este error es parecido al de NameError pero para las key de los diccionarios)
'''

# TypeError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 4 + '3'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>>

un clasico, en este caso se esta intentado sumar 4(q tiene tipo int) con "3"(q tiene tipo string) y vos no podes sumarle a un numero una palabra ni concatenar un numero a una palabra, para solucionarlo hacer q todo tenga el mismo tipo
'''

# ImportError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import power
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'power' from 'math'
>>>

la funcion q se intenta imporatar del modulo math es pow pero se la esta imporatando como power
'''

# ValueError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> int('12a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '12a'
>>>

en esta caso se intenta convertir a int "12a" lo cual no es posible ya q tiene una "a", el metodo int te permite tomar un string (q sean numeros y solo numeros) y convertirlo a intero, para solucionarlo saca la "a" de "12a"
'''

# ZeroDivisionError
'''
asabeneh@Asabeneh:~$ python
Python 3.9.6 (default, Jun 28 2021, 15:26:21)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>>

otro clasico, intentar dividir por cero, en matematica no se puede, por lo cual en programacion tampoco
'''
